### ISSUE TITLE
Asymmetric `provider_settings` show changes

### ISSUE THREAD

**Issue by joscha** [saymedia/terraform-buildkite#14]
I introduced `provider_settings` (see https://buildkite.com/docs/rest-api/pipelines) to allow changes on the pipeline, however this is only the format used for a `POST/PUT` - when using a `GET`, those settings are mangled into a map `provider`, e.g.:

```json
  "provider": {
    "id": "github",
    "webhook_url": "https://webhook.buildkite.com/deliver/xxx",
    "settings": {
      "publish_commit_status": true,
      "build_pull_requests": true,
      "build_pull_request_forks": false,
      "build_tags": false,
      "publish_commit_status_per_step": false,
      "repository": "acme-inc/my-pipeline",
      "trigger_mode": "code"
    }
  },
```

together with some immutable state (e.g. `repository`). Unfortunately that means that the map definition is off, which means that changes are shown on a plan:

```
~ buildkite_pipeline.test
    default_branch:                                             "master" => ""
    provider_settings.%:                                        "3" => "0"
    provider_settings.pull_request_branch_filter_configuration: "" => ""
    provider_settings.repository:                               "joscha/test" => ""
    provider_settings.trigger_mode:                             "code" => ""
```

I think the right way is to make the settings less generic (currently, they are all `bool`, but that's not even true for `"trigger_mode"` for example) and make those parts of the map all optional.
@apparentlymart do you have any recommendation/experience on how to deal with such an asymmetry between local state, push format and read format.

**Comment by apparentlymart** [comment]
Usually in Terraform providers it's preferred to mimic the structure of the underlying system, but in the past there have definitely been weird cases like this in other providers where there's no standard model used for all operations. This leaves us with a few choices:

* Try to invent a common subset or abstraction over the two such that they *can* be treated the same when writing and reading, and then add extra code to the resource implementation to transform the different API formats to the schema format. This is the most common approach, and generally easiest to document/use since most of the time Terraform user's aren't intimately familiar with the underlying APIs anyway, and so small differences aren't a big deal.
* Use separate attributes for reading and writing, with the ones for reading marked as `Computed`. This is more confusing to use so I would suggest it only if the read and write schema are so divergent that mapping them onto a single schema is not possible. It can also present issues for tracking drift since there would presumably be some parts of the data that are not updated by `Read`.

I'm honestly not very familiar with this part of the Buildkite API since Say Media doesn't use Github for internal repository hosting, so I'm not sure which of the above is right here but I would definitely lean towards the first option.

It looks like a further complexity here is that the set of settings here can vary based on which provider is in use. Terraform's schema system is not good at dealing with this sort of dynamic structure, so there have been some compromises taken in the past:

* Make the dynamic data structure be represented in Terraform as a string containing some JSON. The resource implementation then unmarshalls it and uses it, so the types are not visible to the Terraform schema layer. This is an awkward UX but it's been the most common solution.
* Use a nested block structure with a name that implies a type, like this:

```hcl
resource "buildkite_pipeline" "example" {
  # ...

  github_settings {
    # github-specific settings here
  }
}
```

In this case we can write out the schema for each possible set of provider settings and then enforce within the provider that only one settings block is allowed regardless of types. Terraform itself probably wouldn't  be able to verify that the right settings block is chosen for the given repository URL, but that could be addressed in documentation.

**Comment by joscha** [comment]
As a workaround this can be added to the terraform definition:

```
  lifecycle {
    # TODO remove this once https://github.com/saymedia/terraform-buildkite/issues/14 has been fixed
    ignore_changes = ["provider_settings"]
  }
```
