### ISSUE TITLE
Is anyone maintaining this repo?

### ISSUE THREAD

**Issue by yahuio** [saymedia/terraform-buildkite#25]
Got a PR submitted for a few days without any response.

https://github.com/saymedia/terraform-buildkite/pulls

**Comment by apparentlymart** [comment]
Hi @yahudev! Thanks for working on those changes.

I think it's fair to say that this provider is effectively frozen for the moment, because its former maintainers at Say Media don't work there anymore (including myself) and I assume the provider is still working well enough to meet their needs. (Anyone who works at the company still: feel free to correct me!)

Although I am still a contributor here in principle, I don't have a Buildkite development environment set up right now in order to review and test contributions, and my time is of course focused on my _new_ day job.

For the time being, I think the best path would be to fork this repository (which is permitted by its MIT license) and apply your changes to your own copy, which you can then use in place of the releases here.

**Comment by yahuio** [comment]
sure thing, already did that. If someone would redirect people visiting this repo to ours that would worth a thing. Since from my understanding this isn't working due to buildkite API updated.

**Comment by yahuio** [comment]
FYR Duplicated this repo instead, just to assure this fixes are benefits the community. Let me know if there's any concern.

https://github.com/yougroupteam/terraform-buildkite

**Comment by hattorious** [comment]
@yahudev Thank you! I'll update the README with a link to your provider. Additionally I have access to an OSS buildkite project for testing this provider so if you or your team would like access to that as well, please let me know.
