### ISSUE TITLE
Remote state for steps not updated

### ISSUE THREAD

**Issue by joscha** [saymedia/terraform-buildkite#9]
Currently, only the remote state for the main pipeline fields is updated/compared. The defined steps are not taken into account. As such, terraform apply won't show changes if the local state has let's say three steps and two of them were already deleted manually in  buildkite. I suspect this has something to do with the way we compare the remote state to the local state, as such I can only assume it's because the steps are a sub-resource that doesn't get picked up. @apparentlymart can you point me to where I need to make changes and/or an example of another provider that does something similar?

**Comment by apparentlymart** [comment]
Hmm interesting... diffing is supposed to happen automatically, but this could be caused by the `ReadPipeline` function not correctly updating the steps, and indeed it seems like it's being completely ignored:
https://github.com/saymedia/terraform-buildkite/blob/master/buildkite/resource_pipeline.go#L237

Updating set attributes is more complex than updating primitives. I expect what will be needed here is to build a `[]interface{}` containing `map[string]interface{}` members whose keys match the `step` block arguments, and then pass the entire structure as `d.Set("step", stepData)`. This can take some fidgeting to get right, since the `Set` function is able to unpack data structures like this but can be a bit temperamental about exactly what types are used for the members.

**Comment by joscha** [comment]
Got it. That explains why simply adding the steps to the update function didn't work for me. Will try to fix it later - related: are there any good examples on how to test terraform providers I'm the wild? Currently I run it against a real buildkite org, but it would be great if something fiddly like the steps could be done as a fixture.

**Comment by apparentlymart** [comment]
The "official" Terraform providers have automatic acceptance tests which apply real configurations against the real APIs and verify that they behave as expected, but we didn't do that here because it's not really possible to set aside a test account for Buildkite without paying extra for it. :/

If you were willing to run them against your "real" account then you could potentially follow a similar pattern as the providers built in to Terraform. For example, the `rundeck_project` one is a reasonably straightforward case:
https://github.com/hashicorp/terraform/blob/master/builtin/providers/rundeck/resource_project_test.go

There's some more info on this in the contributing guide:
https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#writing-an-acceptance-test

I expect running them will look a bit different for a provider that doesn't live in the Terraform repository. Hopefully it will be sufficient to just run the following from the `$GOPATH/src/github.com/hashicorp/terraform` directory:

```
make testacc TEST=github.com/saymedia/terraform-buildkite/buildkite
```

This makefile target is just a thin wrapper around running `go test` with an environment variable set to confirm that we want to run potentially-expensive tests. In the case of buildkite there isn't a per-pipeline cost so it's not a huge deal, but this mechanism is oriented towards providers like AWS where there's often a per-hour charge for resources under test.

**Comment by joscha** [comment]
>  but we didn't do that here because it's not really possible to set aside a test account for Buildkite without paying extra for it.

@toolmantim, is that something you could provide free of charge for this open source project?

**Comment by apparentlymart** [comment]
Funnily enough I sent the Buildkite folks a note about this earlier today since I didn't have a good way to test your PRs. :grinning:

**Comment by joscha** [comment]
> Funnily enough I sent the Buildkite folks a note about this earlier today since I didn't have a good way to test your PRs. 😀

haha, nice! Go team! ✋

**Comment by lox** [comment]
We're happy to provide a free open-source account, if someone wants to create an org and email me at lachlan@buildkite.com

**Comment by joscha** [comment]
@apparentlymart as the owner of this repo, I think that ^ would be you :)

**Comment by apparentlymart** [comment]
I do personally now have a comped account to test with, though I got the impression that this would be available to others who wanted to work on this provider too, as long as it doesn't end up getting use for "real" work. :grinning:

**Comment by joscha** [comment]
Yes, I think so. I will create an org.
